apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-awesome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-awesome-app
  strategy:
    blueGreen:
      activeService: my-awesome-app
      previewService: my-awesome-app-preview
      # previewReplicaCount: 1
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: my-awesome-app
    spec:
      containers:
      - name: my-awesome-app
        image: sdevang/my-awesome-app:0.1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5001