apiVersion: v1
kind: Service
metadata:
  name: my-awesome-app
spec:
  selector:
    app: my-awesome-app
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: my-awesome-app-preview
spec:
  selector:
    app: my-awesome-app
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer