commonLabels:
  env: pre-production
patchesStrategicMerge:
- replica_count.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: default
images:
- name: sdevang/my-awesome-app
  newName: sdevang/my-awesome-app
  newTag: 0.1.0
